Initial wording for shape rendering
lottie/lottie-spec pull request #16
Opened 2024-02-07 15:09 UTC by mbasaglia

Adds wording for shape algorithms. I used BCP 14 words to specify compliance requirements.

2024-02-07 15:12 UTC, mbasaglia commented
This SHOULD match lottie-web output.

2024-02-07 21:29 UTC, b-wils approved these changes

2024-02-07 21:29 UTC, b-wils commented on docs/index.md
> +Since Lottie uses JSON, basic JSON knowledge is required to understand the specidification.
Typo: speci**d**ification

2024-02-09 15:06 UTC, fmalita requested changes
Thanks Mattia, this is awesome!

2024-02-10 08:26 UTC, mbasaglia commented on docs/specs/shapes.md
> +
I reworded trim path rendering, hopefully it makes more sense now

2024-02-10 11:36 UTC, mbasaglia commented
As a sanity check, I've written this script that given rendering instructions as per the specs, renders a lottie path shape: https://gist.github.com/mbasaglia/5e82cbbe64bbbd3ce96aadb0f952b1e9

Perhaps it would be useful to add it to the github actions to verify the instructions make sense and such but it would need more work for that.

2024-02-11 21:17 UTC, mbasaglia commented
Shapes as rendered from the instructions:
![rect](https://github.com/lottie/lottie-spec/assets/2465791/f4d23c63-fa01-4fea-a0b0-0dd3ff798fdf)
![ellipse](https://github.com/lottie/lottie-spec/assets/2465791/442d0a4e-a0d3-4954-b910-bf9cd0897999)

2024-02-12 02:32 UTC, fmalita approved these changes

2024-02-13 14:47 UTC, kudanai approved these changes

2024-02-13 18:45 UTC, merged